--Complete your queries below--


--**Create skill table**



--**Create city table**



-- **Create venue table**



--**Create team table**



-- **Create player table**

-- **Create outcome table**

-- **Create innings table**

-- **Create game table**

-- **Create umpire table**

-- **Create umpire_type table**

-- **Create game_umpire_type table**

-- **Create wicket_type table**

-- **Change delivery table**

-- **Change wicket table**

-- **Create extratype table**

-- **Create extradelivery table**

-- **Alter column name id**

-- **Alter column name city**

-- **Alter column name caption**

-- **Delete column status**

-- **Drop table delivery**

-- **Drop table game**

-- **Alter column name innings_number**

-- **Alter column name wickets**

-- **Drop table extratype**
CREATE TABLE skill(
ID NUMBER(11),
NAME VARCHAR(20),
CONSTRAINT SKILL_PK PRIMARY KEY (ID));

CREATE TABLE CITY(
ID NUMBER(11),
NAME VARCHAR(100),
CONSTRAINT CITY_PK PRIMARY KEY (ID)
);


CREATE TABLE VENUE(
ID INT,
NAME VARCHAR(100),
CITY_ID NUMBER(11),
CONSTRAINT VENUE_PK PRIMARY KEY (ID),
CONSTRAINT VENUE_FK FOREIGN KEY (CITY_ID) 
REFERENCES CITY(ID)
);
DROP TABLE TEAM;
CREATE TABLE TEAM(
ID INT,
NAME VARCHAR(100),
COACH VARCHAR(100),
HOME_CITY_ID INT,
CAPTAIN INT,
CONSTRAINT TEAM_PK PRIMARY KEY (ID),
CONSTRAINT TEAM_FK FOREIGN KEY (HOME_CITY_ID)
REFERENCES CITY(ID)
);
DROP TABLE PLAYER;
CREATE TABLE PLAYER(
ID INT,
NAME VARCHAR(100),
COUNTRY VARCHAR(100),
SKILL_ID INT,
TEAM_ID INT,
CONSTRAINT PLAYER_PK PRIMARY KEY (ID),
CONSTRAINT PLAYER_FK1 FOREIGN KEY (SKILL_ID)
REFERENCES SKILL(ID),
CONSTRAINT PLAYER_FK2 FOREIGN KEY (TEAM_ID)
REFERENCES TEAM(ID)
);
DROP TABLE OUTCOME;
CREATE TABLE OUTCOME(
ID INT,
STATUS VARCHAR(100),
WINNER_TEAM_ID INT,
WICKETS INT,
RUNS INT,
PLAYER_OF_MATCH INT,
CONSTRAINT OUTCOME_PK PRIMARY KEY (ID),
CONSTRAINT OUTCOME_FK1 FOREIGN KEY (WINNER_TEAM_ID)
REFERENCES TEAM(ID),
CONSTRAINT OUTCOME_FK2 FOREIGN KEY (PLAYER_OF_MATCH)
REFERENCES PLAYER(ID)
);
CREATE TABLE INNINGS(
ID INT,
INNINGS_NUMBER INT,
BATTING_TEAM_ID INT,
CONSTRAINT INNINGS_PK PRIMARY KEY (ID),
CONSTRAINT INNINGS_FK FOREIGN KEY (BATTING_TEAM_ID)
REFERENCES TEAM(ID)
);
DROP TABLE GAME;
CREATE TABLE GAME(
ID INT,
GAME_DATE DATE NOT NULL,
TEAM_ID_1 INT NOT NULL,
TEAM_ID_2 INT NOT NULL,
VENUE_ID INT NOT NULL,
OUTCOME_ID INT NOT NULL,
FIRST_INNINGS_ID INT NOT NULL,
SECOND_INNINGS_ID INT NOT NULL,
CONSTRAINT GAME_PK PRIMARY KEY (ID),
CONSTRAINT GAME_FK FOREIGN KEY (TEAM_ID_1)
REFERENCES TEAM(ID),
CONSTRAINT GAME_FK1 FOREIGN KEY (TEAM_ID_2)
REFERENCES TEAM(ID),
CONSTRAINT GAME_FK2 FOREIGN KEY (VENUE_ID)
REFERENCES VENUE(ID),
CONSTRAINT GAME_FK3 FOREIGN KEY (OUTCOME_ID)
REFERENCES OUTCOME(ID),
CONSTRAINT GAME_FK4 FOREIGN KEY (FIRST_INNINGS_ID)
REFERENCES TEAM(ID),
CONSTRAINT GAME_FK5 FOREIGN KEY (SECOND_INNINGS_ID)
REFERENCES TEAM(ID)
);
DROP TABLE UMPIRE;
CREATE TABLE UMPIRE(
ID INT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL
);
DROP TABLE UMPIRE_TYPE;
CREATE TABLE UMPIRE_TYPE(
ID INT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL
);
CREATE TABLE GAME_UMPIRE_TYPE(
ID INT PRIMARY KEY,
GAME_ID INT,
UMPIRE_ID INT,
UMPIRE_TYPE_ID INT,

CONSTRAINT GAME_UMPIRE_TYPE_FK FOREIGN KEY (GAME_ID)
REFERENCES GAME(ID),
CONSTRAINT GAME_UMPIRE_TYPE_FK1 FOREIGN KEY (UMPIRE_ID)
REFERENCES UMPIRE(ID),
CONSTRAINT GAME_UMPIRE_TYPE_FK2 FOREIGN KEY (UMPIRE_TYPE_ID)
REFERENCES UMPIRE_TYPE(ID)
);
CREATE TABLE WICKET_TYPE(
ID INT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL
);
CREATE TABLE DELIVERY(
ID INT PRIMARY KEY,
INNINGIS_ID INT NOT NULL,
OVER INT,
BALL INT,
BATSMAN_ID INT NOT NULL,
BOWLER_ID INT NOT NULL,
NON_STRIKER_ID INT NOT NULL,
RUNS INT,
CONSTRAINT DELIVERY_FK FOREIGN KEY (INNINGIS_ID)
REFERENCES INNINGS(ID),
CONSTRAINT DELIVERY_FK1 FOREIGN KEY (BATSMAN_ID)
REFERENCES PLAYER(ID),
CONSTRAINT DELIVERY_FK2 FOREIGN KEY (BOWLER_ID)
REFERENCES PLAYER(ID),
CONSTRAINT DELIVERY_FK3 FOREIGN KEY (NON_STRIKER_ID)
REFERENCES PLAYER(ID)
);
CREATE TABLE WICKET(
ID INT PRIMARY KEY,
DELIVERY_ID INT,
WICKET_TYPE_ID INT,
PLAYER_ID INT,
FIELDER_ID INT,
CONSTRAINT WICKET_FK FOREIGN KEY (DELIVERY_ID)
REFERENCES DELIVERY(ID),
CONSTRAINT WICKET_FK1 FOREIGN KEY (WICKET_TYPE_ID)
REFERENCES WICKET_TYPE(ID),
CONSTRAINT WICKET_FK2 FOREIGN KEY (PLAYER_ID)
REFERENCES PLAYER(ID)
);
CREATE TABLE EXTRA_TYPE(
ID INT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL
);
CREATE TABLE EXTRADELIVERY(
ID INT PRIMARY KEY,
DELIVERY_ID INT,
EXTRA_TYPE_ID INT,
RUNS INT,
CONSTRAINT EXTRADELIVERY_FK FOREIGN KEY (DELIVERY_ID)
REFERENCES DELIVERY(ID),
CONSTRAINT EXTRADELIVERY_FK1 FOREIGN KEY (EXTRA_TYPE_ID)
REFERENCES EXTRATYPE(ID)
);

